services:
  postgres:
    container_name: td_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: amouri
      POSTGRES_PASSWORD: amouri
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 2345:5432
    networks:
      - to-do-net
    restart: unless-stopped

  pgadmin:
    container_name: td_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - to-do-net
    restart: unless-stopped

  mail-dev:
    container_name: td_mail_dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - to-do-net

networks:
  to-do-net:
    driver: bridge

volumes:
  postgres:
  pgadmin:

