spring:
  datasource:
    url: jdbc:postgresql://td_pg_sql:5432/to_do
    username: amouri
    password: amouri
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 465
    username: souhail
    password: souhail
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: "*"
        starttls:
          enabled: true
    protocol: smtp

server:
  port: 8088